### ISSUE TITLE
Waveform

### ISSUE THREAD

**Issue by caemor** [TeXitoi/il3820#1]
While porting your rusty-clock to my waveshare-crate I saw that you are using a different waveform for the full refresh. (https://github.com/TeXitoi/il3820/blob/master/src/lib.rs#L81 vs https://github.com/caemor/epd-waveshare/blob/master/src/type_a/constants.rs#L3).  Can you remember why you choose these ones?

Btw: I got your rusty-clock running (with both versions). It looks great :+1: will hopefully be able to make a few pics until the weekend

**Comment by TeXitoi** [comment]
It's a faster full refresh lut taken from a C driver. It claims to be faster but a bit less effective. I'm not found of the result as I still have some goshting after the midnight full refresh, but didn't take the time to test the other one.

**Comment by TeXitoi** [comment]
Taken from https://github.com/ZinggJM/GxEPD/blob/master/src/GxGDEH029A1/GxGDEH029A1.cpp#L27-L32 I think.
